name: flutter_welcome_kit
description: A lightweight and customizable onboarding tour guide for Flutter apps with spotlight overlays and step-by-step tooltips.
version: 1.0.0
homepage: https://github.com/your-username/flutter_welcome_kit
repository: https://github.com/your-username/flutter_welcome_kit
issue_tracker: https://github.com/your-username/flutter_welcome_kit/issues

environment:
  sdk: ^3.8.0-278.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


