name: Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.8.0-278.1.beta'
          channel: 'beta'
      
      - name: Enable Flutter Web
        run: flutter config --enable-web
      
      - name: Install Dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get
      
      - name: Build Example
        working-directory: ./example
        run: |
          flutter build web --release --base-href '/flutter_welcome_kit/'
          cp -r build/web/* ./
          touch build/web/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
          force_orphan: true
          cname: # Remove this line if you don't have a custom domain